version: '3.9'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Felipe123
      MYSQL_DATABASE: imobiliaria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: imobiliaria-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: imobiliaria
      DB_USER: root
      DB_PASS: Felipe123

volumes:
  db_data:
